name = "TestingDeps"
uuid = "1615a2ea-5393-4104-a93f-a8aee4a27adf"
authors = ["Robert Moss <rmoss92@gmail.com>"]
version = "0.1.0"

[deps]
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
